name: Docker Build

on:
  push:
    branches:
      - 'master'
      - 'v3-branch'
  release:
    types: [released]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --use-container

